---
- name: Include f5devcentral.bigiq_migrate_apps role
  debug:
    msg: 
      - "This is the tenant: {{iqtenant}}"
      - "This is the target: {{target_address}}"
      - "This is the new target: {{ new_tgt_addr }}"

- name: Get Config set for Application Service
  uri:
    url: https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/global/config-sets?$filter=tenantReference.link%20eq%20'{{ cs_selfLink }}'
    method: GET
    timeout: "{{ timeout }}"
    validate_certs: "{{ provider.validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    status_code: 200, 202
  register: cs_response

- name: Get the application link to the services in the tenant
  set_fact:
    #cs_name: "{{ cs_response | json_query(cn_query) }}"
    app_link: "{{ cs_response | json_query(app_query) }}"
  vars: 
    #cn_query: "json.items[0].configSetName"
    app_query: "json.items[0].applicationReference.link"

- debug:
    msg: 
      - "{{ app_link }}"

- name: Get Application informatin
  uri:
    url: https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/global/global-apps?$filter=selfLink%20eq%20'{{ app_link }}'
    method: GET
    timeout: "{{ timeout }}"
    validate_certs: "{{ provider.validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    status_code: 200, 202
  register: app_response

- name: Get the Application name
  set_fact:
    move_to_app: "{{ app_response | json_query(app_name_query) }}"
  vars: 
    app_name_query: "json.items[0].name"

- debug:
    var: move_to_app

- name: Include f5devcentral.bigiq_migrate_apps role
  tags:
    - iqrole
  include_role:
    name: f5devcentral.bigiq_migrate_apps
  vars:
    dir_as3: ~/tmp
    device_address: "{{ target_address }}"
    tenant_to_migrate: "{{ iqtenant }}"
    new_device_address: "{{ new_tgt_addr }}"
    new_tenant_name: "{{ iqtenant }}_new"
    new_bigiq_app_name: "{{ move_to_app }}"
  when: target_address != 'undefined'